apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monorepo-1
  description: Monorepo 1
  annotations:
    github.com/project-slug: gobriango19/monorepo-1
spec:
  type: website
  lifecycle: experimental
  owner: brian
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: monorepo-1-sub-locations
spec:
  type: url
  targets:
    - ./monorepo-1-sub-1/backstage.yaml
    - ./monorepo-1-sub-2/backstage.yaml
    - ./monorepo-1-sub-3/backstage.yaml